# Generated by Django 5.2.6 on 2025-09-15 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('name', models.CharField(max_length=255, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('name', models.CharField(max_length=100, verbose_name='País')),
                ('DDI_Code', models.CharField(max_length=5, verbose_name='DDI')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('tax_id', models.CharField(max_length=20, verbose_name='ID Fiscal')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('name', models.CharField(max_length=40, verbose_name='Documento Fiscal')),
            ],
            options={
                'verbose_name': 'Documento Fiscal',
                'verbose_name_plural': 'Documentos Fiscais',
            },
        ),
        migrations.CreateModel(
            name='UseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('name', models.CharField(max_length=30, verbose_name='Tipo de uso')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.person')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nome da empresa')),
                ('company_creation_date', models.DateField(verbose_name='Data de Criação da Companhia')),
            ],
            options={
                'verbose_name': 'Pessoa jurídica',
                'verbose_name_plural': 'Pessoas jurídicas',
            },
            bases=('contacts.person',),
        ),
        migrations.CreateModel(
            name='NaturalPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.person')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
            ],
            options={
                'verbose_name': 'Pessoa física',
                'verbose_name_plural': 'Pessoas físicas',
            },
            bases=('contacts.person',),
        ),
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('postal_code', models.CharField(max_length=30, verbose_name='Código postal')),
                ('id_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.city')),
            ],
            options={
                'verbose_name': 'CEP',
                'verbose_name_plural': 'CEPs',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('name', models.CharField(max_length=100, verbose_name='Estado')),
                ('id_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.country')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='id_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.state'),
        ),
        migrations.AddField(
            model_name='person',
            name='tax_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.taxtype'),
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Número de telefone')),
                ('is_main_phone', models.BooleanField(default=False, verbose_name='Telefone principal?')),
                ('id_DDI', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.country')),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.person')),
                ('use_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.usetype')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('email', models.EmailField(max_length=128, verbose_name='Email')),
                ('is_main_email', models.BooleanField(default=False, verbose_name='Email principal?')),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.person')),
                ('use_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.usetype')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('street_name', models.CharField(max_length=120, verbose_name='Rua')),
                ('number', models.CharField(max_length=5, verbose_name='Número')),
                ('addon_address', models.CharField(max_length=200, verbose_name='Complemento')),
                ('is_main_address', models.BooleanField(default=False, verbose_name='Endereço principal?')),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.person')),
                ('id_cep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.postalcode')),
                ('use_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.usetype')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
    ]
