# Generated by Django 5.2.6 on 2025-09-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxtype',
            name='characterLimit',
            field=models.IntegerField(default=20, verbose_name='Limite de caracteres'),
        ),
    ]
