# Generated by Django 5.2.6 on 2025-09-25 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_taxtype_characterlimit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxtype',
            old_name='characterLimit',
            new_name='character_limit',
        ),
    ]
